### ISSUE TITLE
Remover parâmetro de método

### ISSUE THREAD

**Issue by maikenegreiros** [ciebit/news#10]
Na classe  Ciebit\News\Storages\Database\SqlFilters existe o método orderBy, que aceita dois parâmetros, a coluna e a ordem. Creio que a coluna já deveria ter um valor padrão armazenado em uma propriedade.

**Comment by johnnysaymon** [comment]
Mas isso não nos tira a flexibilidade de escolha por qual colunas desejamos ordenar?

**Comment by maikenegreiros** [comment]
Eu não expliquei bem, mas o que considero que seria melhor seria criar um método "setOderBy" para cada coluna, por exemplo: setOrderByDate, setOrderByTitle. 
Da forma como está, tenho que passar o nome da coluna no meu projeto cliente, se por um acaso a estrutura sql desse módulo mudar, vai quebrar a execução lá no cliente

**Comment by johnnysaymon** [comment]
Compreendi. Nesse caso aconselho utilizar constantes públicas para conter o nome dos campos. Fazendo assim:

```php
$storage
->addOrderBy($storage::COLUMN_TITLE, 'ASC')
->addOrderBy($storage::COLUMN_DATETIME, 'DESC');
```
Isso resolve o problema inicial sem adicionar muitos métodos, que efetuam a mesma coisa na classe, e nos dá a opção de adicionar mais de um campo de ordenação. Se quisermos podemos abstrair ainda mais adicionando o segundo parâmetro como constante, assim:

```php
$storage
->addOrderBy($storage::COLUMN_TITLE, $storage::ORDER_ASC)
->addOrderBy($storage::COLUMN_DATETIME, $storage::ORDER_DESC);
```
