### ISSUE TITLE
Alterar forma coletar os dados persistência

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/news#15]
Adicionar dependência do *storage* do módulo *File* para que as consultas de cada módulo ocorram em seus respectivos módulos. Exemplo de uma consulta simples:

```php
$statement->execute();
$newsData = $statement->fetch(PDO::FETCH_ASSOC);
$story = $this->storyStorage->addFilterById($newsData['story_id'])->get();
$cover = $this->fileStorage->addFilterById($newsData['cover_id'])->get();
$labels = $this->getLabelsByStoryId($newsData['cover_id']);

$news = new News($story, new Status($newsData['status']));
$news->setImage($cover);
$news->setLabels($labels);

return $news;
```

Será necessário fazer algumas verificações, o código acima é só para mostrar o objetivo.

**Comment by maikenegreiros** [comment]
@johnnysaymon , nessa linha `$labels = $this->getLabelsByStoryId($newsData['cover_id']);`. O correto seria pegar as labels pelo id de `news` e não de `story`, não é mesmo?

**Comment by johnnysaymon** [comment]
Isso mesmo @maikenegreiros . Acabei errando nesse código. Passei foi o ID da imagem, quando deveria ter passado o ID da `news`.

Dentro desse método aconselho adotar os seguintes passos:

1. Coletar o registro de associações `News` e `Labels` que estão na tabela `cb_news_labels`;
2. Em seguida extrair apenas os *IDs* dos *labels*;
3. Adicionar o filtro por *IDs* ao *storage de Labels*;
4. Retornar a coleção.

**Comment by johnnysaymon** [comment]
Essa abordagem se mostrou inviável pois seria necessário um conhecimento da tabela de `Stories` ou a criação de métodos `get` com lógica pré determinada.

Optei por remover todos os métodos de filtragem que utilizavam propriedades de `Story` conforme pull request #16
